# Generated by Django 4.1.1 on 2022-10-05 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_todo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
